loki:
    url: ENC[AES256_GCM,data:r+mu+4FSOd0mPtFvtJwS1xa8ld0JdHFQ9pJSQYGHToxicDfBa/L9LRApxjgkrrObRVRGp4w=,iv:3td9wC5WGgpiyolmlB2tY4sTfvaim2zF+AR17YgydJA=,tag:C0jIArcPHfv1+oyTYbApYQ==,type:str]
    username: ENC[AES256_GCM,data:cQCxraentEg7oSsg,iv:kcS1740IuJY9itUYewUmWIIkbofae0YzFkuRjPm7fGo=,tag:ory+6nQZt0yETMrOOPFNbA==,type:str]
    password: ENC[AES256_GCM,data:OWA9NJGfTSYT2E4ts+1MMKA9OFhsaT8iUwheaMvC2K6Kb9e61uaaip1bhohWAf0uiQ0tL93zRz7zl6SJ7d+RnIIyEHSXzybznw==,iv:+bL6Qri6DOmPtfDl+9FmnlrMICdElgA+9nOCgtcHH9M=,tag:GbZIRzK9RO5Qb4SRx0ay1w==,type:str]
mimir:
    url: ENC[AES256_GCM,data:z5NPc4Snn7CWU/mY7EYam/kLc0sFZWTg9MI2tCrGw7bYbK98DqQ6xrBtuE35UEjPpMr2QY4V,iv:+rGe9dBqwJoEkbD/jPPjksvnbAywsovT78GSFPvipxQ=,tag:YD20bcLAyUlGahIMm+gsEg==,type:str]
    username: ENC[AES256_GCM,data:/aTe1QCKXzgJtpqI,iv:ScAZpyqu1UjV5B5IB3rKMT1ptxgCytdLvLLm7lXkUII=,tag:MGNDmLqtM4mKyOQri63vFw==,type:str]
    password: ENC[AES256_GCM,data:VbJAjcZcz8on5e3l/s57eug3u9QhxJmfUjkdwP0gTAjuNl8dOcZ9sYD2NINTHeA0Nn1osqaYT4XA6Yy53XPyhXrfOVEw9n8TKlmVqB5J,iv:QJ4TXgg+LIBPOIgMr06wCz2WnVZS99ZysFQuCDeKEUk=,tag:Jb+GsQHOZlvl7t3ippKD2g==,type:str]
sops:
    age:
        - recipient: age1yubikey1qgxj47xg2sxwv95w0zhlqw7ay4qsdltjgura29wd57kmx5hjfdaxxxla29h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IEIwZmwrQSBBZ3FUR01K
            ZHYxQ3QzREFZaVAxTk5MTnRNRUwzVERqMXlWRDJ5Q2JpdmNMQwpGQ1UxOFgrcVdQ
            NlhFQ1ExdnM2R2JBQXB3aGhHNWV0a0NHREtLZEgrVm1ZCi0tLSBPdi9MNnZKNXRr
            bDhoNUJiWU5vUVBxNkJkRDBnUXhEbGpNZmI1SFpScUhzCivcqFM2gMZEJDkB33Ov
            UoxrU8y98GcJj2Y2hV/bbdbJR+PTCYGWYedB2lGYIRgxev/o1ssvNAf/j8g4Zx8z
            2yo=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q0ukp0umwpvky9eamjym59mh42p5nz5q02zvx5mhfy57t6xmnzzm5zvaugq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHExT3lsQSBBcTB4Ukc0
            WXd2VExPWkNHTktDd2hhYUo5emJOOGRtRUwzQk5JSE5jQ1ZQcgpLRzJPb3VGQy81
            dDNFOVlNYnlOT3NabjFmaHFORXVwZFRnWXlMbmFxNlVzCi0tLSBRWnh3em9HWEtr
            anFMcVRFZzBCdXRxQmErWVpQWVg1QXZNWmY0TWdKM1NrCqtvoEFh+MGc7MV5jdxU
            cfPaNvVSzrksNkzAtgvvhAssiQtM0IJhi1wlgh4fcxun1gsc5t3XVBFTTd7GslUQ
            BPg=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1qvm5j08damled24uvgaeveg0znt9f8sr8e8d5e4sdh9j75g9z8wnq6s5lwg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGQyUmkzQSBBaVMwY3lP
            UU9iRTFoVVlkQ09kSEp3U2V4cnZGRG10T3RLZFdZcmJZak1sUwp0cHYzTDJNdkEz
            eFhidHh6am9TS2xVb2ZUcWRwTWRFOHFUc2t1eVVNUUEwCi0tLSAwdXc2YU1lcDg2
            K1R5NHVOalFBb2l5L0lERWFBYnVUd2Q2WGYxZ0VSbVBzCpFCmr6Rgnt7jg14Qjbp
            G9MUSooY+L1CEII2do7NB5m9GvAsOhoxXYRtRjG2Q8PcQhn1qFY+3Rjj/mo55umn
            Y2Q=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yubikey1q236gnfv88v7ln4drft9y7swllwc5la5m9dut57ck8e9kcs0e32zqnqfg8l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGZEQVNRUSBBaFdIcnV4
            c1QyWFB4ajZpYkZ0SFU2ckRuRWJiU01rNEh4Z05ETk94bnNnRwp3ZlpXdE0zdnBa
            YlZvdGtRQTVQRGRoQXpVU292VVgrOUZDa0RyWm9uQUdFCi0tLSBIN0FkT2pHWFZa
            UFpMNjdPTjVvSWszSnh2TTMxSEFyaHlxak1mRjVKT2FVChpCgjhBG5VNgDzJ6eID
            29SkXVLYkeaenQwsxAt0kl6IElkglmNFQ05kWVkA9MaONG3eAV33AHOoFVaYt7pr
            Q/c=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-27T14:24:07Z"
    mac: ENC[AES256_GCM,data:FajVDsvfbfCnPlD8tfroqFR3v4i7Mn0vzdxiSLZRoSe33TRZ3YU/rHLUnk+eCVdlJNwCiSz4oGlKmlN/S0k7Mx5nnFod56MJpFqBuUxdMPUlY9JxjU/29aWazRsVKhaDcroU1bk0NhHYuLlg48Cov0cnzwhSmmXAnP5aAB0hUwk=,iv:N/NM4xAroiHR+Bjgi3XrXUhQtId583FOBkTGbhBizbw=,tag:d+pSXXL+4LjjsnHoD98dpA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
