---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: archive-credentials
  namespace: digital-muon-pipeline
spec:
  type: kv-v2
  refreshAfter: 30s
  vaultAuthRef: static-auth

  mount: digital-muon
  path: isis_archive
  destination:
    name: archive-credentials
    overwrite: true
    create: true
