#
# This is a generated file!
#

---
apiVersion: v1
kind: Secret
metadata:
  name: archive-credentials
  namespace: digital-muon-pipeline
type: Opaque
stringData:
  domain: "ref+sops://src/secrets.yml#/domain"
  username: "ref+sops://src/secrets.yml#/username"
  password: "ref+sops://src/secrets.yml#/password"
---
apiVersion: v1
kind: Namespace
metadata:
  name: digital-muon-pipeline
